### ISSUE TITLE
Use tenacity (or similar) instead of re-implementing a retry function

### ISSUE THREAD

**Issue by marco-c** [mozilla/libmozevent#1]

**Comment by Xk0nSid** [comment]
@marco-c I would like to work on this as my first issue, if it still requires work.

**Comment by marco-c** [comment]
To fix this issue, you just need to remove https://github.com/mozilla/libmozevent/blob/87f8d0e507ac030a142bb06368bca021d174d3ca/libmozevent/utils.py#L24 (and everything used by this function).

**Comment by anandhkishan** [comment]
Hi, @marco-c I would like to contribute. Can you please help me with details on how to create a new branch and raise a PR. Currently, I'm getting 403 when trying to push my changes to remote in a new branch that I have created locally.

**Comment by anandhkishan** [comment]
@marco-c  Can you please take a look into PR that I have created? 
https://github.com/mozilla/libmozevent/pull/60
