### ISSUE TITLE
Monitoring doesn't work when going between instances

### ISSUE THREAD

**Issue by marco-c** [mozilla/libmozevent#17]
E.g. code-review-events uses firefox-ci but triggers some bugbug tasks on community-tc.

**Comment by La0** [comment]
I'm sad :crying_cat_face:

**Comment by marco-c** [comment]
@La0 we should make a new release to use in code-review and code-coverage, and confirm that this issue has been fixed by cfc4fa20aedc2c6c384bc9d2a600e1f6de208564.

**Comment by marco-c** [comment]
Actually, we'll need to implement a fix in code-review too: https://github.com/mozilla/code-review/issues/304.

I'll close this as it is now supported in libmozevent to specify the Taskcluster deployment to use.
