### ISSUE TITLE
Remove support for restarting tasks in monitoring

### ISSUE THREAD

**Issue by marco-c** [mozilla/libmozevent#39]
We shouldn't assume `TASKCLUSTER_NAMESPACE = "project.releng.services.tasks.{task_id}"`.

**Comment by marco-c** [comment]
We could stop using the index altogether and either I) add 'restartable' to the task extra, so we can just load the task directly and don't access the index; II) add a parameter to Monitoring to select the routes which match restartable tasks.

After we do this, we can stop storing `monitoring_restart` data in the index, and we can probably stop indexing to project.releng.services.tasks.XXX.

**Comment by marco-c** [comment]
We could also drop the restarting code, as it's not really being used at the moment.

**Comment by La0** [comment]
Best solution is to remove so we don't try to maintain unused stuff (except if you need it for bugbug !)

**Comment by marco-c** [comment]
I don't need it for bugbug, if you don't need it for the autoland tasks, let's remove it.
