### ISSUE TITLE
Use HIGHEST Pickle protocol in storage and bus

### ISSUE THREAD

**Issue by marco-c** [mozilla/libmozevent#51]
This way we benefit from enhancement in latest Pickle protocol versions (e.g. [protocol 5](https://www.python.org/dev/peps/pep-0574) in Python 3.8).

**Comment by gkprasanth** [comment]
@marco-c 
Hi ,
I have knowledge of basic Python and I am really interested in contributing to this project. DO u think I will be able to work on this issue as a beginner programmer with no experience in open source?

**Comment by marco-c** [comment]
@gkprasanth this was actually already fixed by #61 a while ago :)
