### ISSUE TITLE
Extend mercurial logging

### ISSUE THREAD

**Issue by La0** [mozilla/libmozevent#80]
We should have more logging output available on papertrail on normal usage but also errors.

You can see on that screenshot a bunch of almost empty "Mercurial" log lines.

![Screenshot 2022-09-21 at 16-34-40 54 221 22 242 - Papertrail](https://user-images.githubusercontent.com/101004/191533619-13e701ee-a21f-4ba5-ab9f-bc7f54448a3d.png)

Things to improve:
- actually log the raw mercurial output (some of it is already capture, but not all it seems - maybe stdout only ?)
- make sure structlog is reported on papertrail (it's not the case right now and we lose the error details)

**Comment by vrigal** [comment]
The first part does not seems related to the mercurial module, but the structlog configuration in code review events not displaying the extra arguments. I opened a PR: https://github.com/mozilla/code-review/pull/1333

**Comment by vrigal** [comment]
> make sure structlog is reported on papertrail (it's not the case right now and we lose the error details)

About this point, everything seems to be configured correctly (in code review events and bot CLI). I replaced the TCP port to a simple dump (`logging.StreamHandler` instead of `logging.handlers.SysLogHandler`).
```python
>>> from log import init_logger, structlog, logging
>>> init_logger(
>>>     "test_project", channel="chan 1", PAPERTRAIL_HOST="127.0.0.1", PAPERTRAIL_PORT=3456
>>> )
>>> logger = structlog.get_logger(__name__)
>>> logger.error("AAAAAAAAA", a="b")

2022-09-26 16:37:35.000123 [ERROR   ] <ipython-input-1-c200f72242e2>: msg='AAAAAAAAA' extra={'a': 'b'}
code-review/chan 1/test_project: 2022-09-26 16:37:35 <ipython-input-1-c200f72242e2>: msg='AAAAAAAAA' extra={'a': 'b'}
```

Are `PAPERTRAIL_HOST` and `PAPERTRAIL_PORT` correctly defined in the settings ?
